# Generated by Django 4.1.7 on 2023-03-28 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarBodyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CarColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=20)),
                ('birthday', models.DateField()),
                ('registered_on', models.DateTimeField(auto_now_add=True)),
                ('reg_doc_number', models.CharField(max_length=9, unique=True)),
                ('photo', models.ImageField(upload_to='img/')),
                ('free', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('logo', models.ImageField(upload_to='img/')),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('weight', models.IntegerField()),
                ('engine_capacity', models.FloatField()),
                ('engine_power', models.IntegerField()),
                ('body_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxi_depot.carbodytype')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxi_depot.manufacturer')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_year', models.IntegerField()),
                ('photo', models.ImageField(upload_to='img/')),
                ('reg_number', models.CharField(max_length=9, unique=True)),
                ('free', models.BooleanField()),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxi_depot.carcolor')),
                ('drivers', models.ManyToManyField(related_name='cars', to='taxi_depot.driver')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxi_depot.carmodel')),
            ],
        ),
    ]
